SECRET_KEY: "r25BdIag7v7GRW0CXCntF4KRQ1JuGgNg3mM6imXSNaY"
ALGORITHM: "HS256"
TOKEN_EXPIRATION_HOURS: 24
USERNAME: "admin"
PASSWORD: "admin"
MaxNumEmails: 100
HOST: "0.0.0.0"
PORT: 8888
SSL_CERTFILE: "cert.pem"
SSL_KEYFILE: "key.pem"
